version: '3'

services:
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    # environment:
    #   MYSQL_ROOT_PASSWORD: changeme
    ports:
      - 3306:3306

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  vault:
    image: vault:latest
    ports:
      - "8200:8200"
    environment:
      SKIP_SETCAP: 1
      VAULT_TOKEN: changeme
      VAULT_DEV_ROOT_TOKEN_ID: changeme

volumes:
  db_data:
  redis_data:
