{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "exchange.serviceAccountName" . }}
  labels:
{{ include "exchange.labels" . | indent 4 }}
{{- end -}}
