# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.5'

gem 'dotenv-rails', groups: %i[development test]

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.2', '>= 6.0.2.2'
# Use mysql as the database for Active Record
gem 'mysql2', '>= 0.5'

gem 'activerecord-import'

# Use Puma as the app server
gem 'puma', '~> 4.3'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.6', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

# ws and http client
gem 'faye-websocket'
gem 'eventmachine'
gem 'em-websocket'
gem 'faraday'
gem 'faraday_middleware'

gem 'rbtree'
# gem 'sql-parser', github: 'FlowerWrong/sql-parser'
# gem 'http_parser.rb'

gem 'method-not-implemented'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]

  gem 'awesome_print'
  gem 'pry-byebug'
  gem 'pry-rails'
end

group :development do
  gem 'listen'

  gem 'spring'
  gem 'spring-watcher-listen'
end
