# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'dotenv-rails', groups: %i[development test]

gem 'rails', '~> 6.0.3.1'
gem 'rails-i18n', '~> 6.0.0'

gem 'mysql2', '>= 0.5'

gem 'activerecord-import'

gem 'puma', '~> 4.3'

gem 'bootsnap', '>= 1.4.6', require: false

gem 'rack-cors'

# ws and http client
gem 'faye-websocket'
gem 'eventmachine'
gem 'em-websocket'
gem 'faraday'
gem 'faraday_middleware'

gem 'rbtree'
# gem 'sql-parser', github: 'FlowerWrong/sql-parser'
# gem 'http_parser.rb'

gem 'method-not-implemented'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]

  gem 'awesome_print'
  gem 'pry-byebug'
  gem 'pry-rails'
end

group :development do
  gem 'listen'

  gem 'spring'
  gem 'spring-watcher-listen'
end
