# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.0'
# Use mysql as the database for Active Record
gem 'mysql2', '>= 0.5'
# Use Puma as the app server
gem 'puma', '~> 4.2'

gem 'bcrypt'
gem 'httparty'

gem 'redis', '~> 4.1'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4', require: false

gem 'rack-cors'

gem 'grape'
gem 'grape-entity'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]

  # test gem
  gem 'rspec-rails'

  # development helper gem
  gem 'awesome_print'
  gem 'dotenv-rails'

  gem 'pry-byebug'
  gem 'pry-doc'
  gem 'pry-rails'

  gem 'rubocop-rails'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'

  gem 'annotate'

  gem 'grape-swagger'
  gem 'grape-swagger-entity'
  gem 'grape-swagger-rails'
  gem 'grape-swagger-representable'
end
