# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.2.2'
# Use mysql as the database for Active Record
gem 'mysql2', '>= 0.5'
# Use Puma as the app server
gem 'puma', '~> 4.3'

gem 'bcrypt'
gem 'httparty'

gem 'redis'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4', require: false

gem 'rack-cors'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]

  # development helper gem
  gem 'awesome_print'
  gem 'dotenv-rails'

  gem 'pry-byebug'
  gem 'pry-doc'
  gem 'pry-rails'

  gem 'rubocop-rails'
end

group :test do
  gem 'rspec-rails'
end

group :development do
  gem 'listen'

  gem 'spring'
  gem 'spring-watcher-listen'

  gem 'annotate'
end
