# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.5'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.2', '>= 6.0.2.2'
# Use mysql as the database for Active Record
gem 'mysql2', '>= 0.4.4'
# Use Puma as the app server
gem 'puma', '~> 4.3'

gem 'bcrypt'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.2', require: false

gem 'rbtree'

gem 'grape'
gem 'grape-entity'
gem 'grape_logging'
# gem 'grape-swagger'
# gem 'grape-swagger-ui'
# gem 'grape-swagger-entity'

# gem 'rack-attack'
# gem 'rack-cors'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]

  gem 'awesome_print'
  gem 'pry-rails'

  gem 'rspec-rails', '~> 4.0.0'
  gem 'factory_bot_rails'
end

group :test do
  gem 'database_cleaner-active_record'
  gem 'database_cleaner-redis'

  gem 'fakeredis'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
