# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.5'

gem 'dotenv-rails', groups: %i[development test]

gem 'rails', '~> 6.0.2', '>= 6.0.2.2'

gem 'mysql2', '>= 0.5'

gem 'puma', '~> 4.3'

gem 'bcrypt'
gem 'jwt'

gem 'redis'
gem 'hiredis'

gem 'bunny'

gem 'aasm'

gem 'hashie'
gem 'method-not-implemented'

gem 'faraday'
gem 'better-faraday'
gem 'faraday_middleware'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4', require: false

gem 'rbtree'

gem 'grape'
gem 'grape-entity'
gem 'grape_logging'
# gem 'grape-swagger'
# gem 'grape-swagger-ui'
# gem 'grape-swagger-entity'

# gem 'rack-attack'
# gem 'rack-cors'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]

  gem 'awesome_print'
  gem 'pry-rails'
  gem 'pry-byebug'

  gem 'rspec-rails', '~> 4.0.0'
  gem 'factory_bot_rails'
end

group :test do
  gem 'database_cleaner-active_record'
  gem 'database_cleaner-redis'

  gem 'fakeredis'
end

group :development do
  gem 'listen'
  gem 'spring'
  gem 'spring-watcher-listen'

  gem 'annotate'
end
